# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 606)
        MainWindow.setMinimumSize(QtCore.QSize(755, 573))
        MainWindow.setStyleSheet("background-color: rgb(77, 63, 75);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 491, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.btnconsulta = QtWidgets.QPushButton(self.groupBox)
        self.btnconsulta.setGeometry(QtCore.QRect(30, 40, 75, 23))
        self.btnconsulta.setObjectName("btnconsulta")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 40, 51, 23))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(390, 40, 51, 23))
        self.pushButton.setObjectName("pushButton")
        self.label1 = QtWidgets.QLabel(self.groupBox)
        self.label1.setGeometry(QtCore.QRect(340, 20, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(170, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(234, 22, 70);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.labelst1 = QtWidgets.QLabel(self.centralwidget)
        self.labelst1.setGeometry(QtCore.QRect(370, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelst1.setFont(font)
        self.labelst1.setObjectName("labelst1")
        self.resultadoId = QtWidgets.QLabel(self.centralwidget)
        self.resultadoId.setGeometry(QtCore.QRect(460, 150, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.resultadoId.setFont(font)
        self.resultadoId.setObjectName("resultadoId")
        self.labelst2 = QtWidgets.QLabel(self.centralwidget)
        self.labelst2.setGeometry(QtCore.QRect(370, 180, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelst2.setFont(font)
        self.labelst2.setObjectName("labelst2")
        self.labelst3 = QtWidgets.QLabel(self.centralwidget)
        self.labelst3.setGeometry(QtCore.QRect(370, 230, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelst3.setFont(font)
        self.labelst3.setObjectName("labelst3")
        self.labelst4 = QtWidgets.QLabel(self.centralwidget)
        self.labelst4.setGeometry(QtCore.QRect(370, 270, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelst4.setFont(font)
        self.labelst4.setObjectName("labelst4")
        self.labelst5 = QtWidgets.QLabel(self.centralwidget)
        self.labelst5.setGeometry(QtCore.QRect(370, 300, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelst5.setFont(font)
        self.labelst5.setObjectName("labelst5")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(30, 90, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.resultadoName = QtWidgets.QLabel(self.centralwidget)
        self.resultadoName.setGeometry(QtCore.QRect(460, 180, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.resultadoName.setFont(font)
        self.resultadoName.setObjectName("resultadoName")
        self.resultadomin = QtWidgets.QLabel(self.centralwidget)
        self.resultadomin.setGeometry(QtCore.QRect(420, 270, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.resultadomin.setFont(font)
        self.resultadomin.setObjectName("resultadomin")
        self.resultadomax = QtWidgets.QLabel(self.centralwidget)
        self.resultadomax.setGeometry(QtCore.QRect(420, 300, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.resultadomax.setFont(font)
        self.resultadomax.setObjectName("resultadomax")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 520, 121, 31))
        self.pushButton_3.setStyleSheet("background-color: rgb(55, 46, 56);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 520, 121, 31))
        self.pushButton_4.setStyleSheet("background-color: rgb(55, 46, 56);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 130, 311, 311))
        self.label.setStyleSheet("background-image: url(:/prefijoNuevo/asteroid2.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/prefijoNuevo/asteroid2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.labelst6 = QtWidgets.QLabel(self.centralwidget)
        self.labelst6.setGeometry(QtCore.QRect(370, 330, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelst6.setFont(font)
        self.labelst6.setObjectName("labelst6")
        self.resultadohar = QtWidgets.QLabel(self.centralwidget)
        self.resultadohar.setGeometry(QtCore.QRect(490, 330, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.resultadohar.setFont(font)
        self.resultadohar.setObjectName("resultadohar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 0, 121, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/prefijoNuevo/logoNasa.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Conexión"))
        self.btnconsulta.setText(_translate("MainWindow", "Consultar"))
        self.pushButton_2.setText(_translate("MainWindow", "<<"))
        self.pushButton.setText(_translate("MainWindow", ">>"))
        self.label1.setText(_translate("MainWindow", "Navegación"))
        self.labelst1.setText(_translate("MainWindow", "ID Asteroide"))
        self.resultadoId.setText(_translate("MainWindow", "Vacío"))
        self.labelst2.setText(_translate("MainWindow", "Nombre"))
        self.labelst3.setText(_translate("MainWindow", "Apróximado del diámetro"))
        self.labelst4.setText(_translate("MainWindow", "Min"))
        self.labelst5.setText(_translate("MainWindow", "Max"))
        self.label2.setText(_translate("MainWindow", "Información sobre la orbita del asteroide"))
        self.resultadoName.setText(_translate("MainWindow", "Vacío"))
        self.resultadomin.setText(_translate("MainWindow", "Vacío"))
        self.resultadomax.setText(_translate("MainWindow", "Vacío"))
        self.pushButton_3.setText(_translate("MainWindow", "Guardar"))
        self.pushButton_4.setText(_translate("MainWindow", "Menu Principal"))
        self.labelst6.setText(_translate("MainWindow", "¿Es Peligroso?"))
        self.resultadohar.setText(_translate("MainWindow", "Vacío"))

import imgs1_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

